export const GAME_FETCH_INITIAL_SETUP_START = "GAME_FETCH_INITIAL_SETUP_START";
export const GAME_FETCH_INITIAL_SETUP_SUCCESS =
  "GAME_FETCH_INITIAL_SETUP_SUCCESS";
export const GAME_FETCH_INITIAL_SETUP_FAIL = "GAME_FETCH_INITIAL_SETUP_FAIL";
export const GAME_CHANGE_PLAYER_NAME = "GAME_CHANGE_PLAYER_NAME";
export const GAME_CELL_CLICKED = "GAME_CELL_CLICKED";
export const GAME_END = "GAME_END";
export const GAME_RESTART = "GAME_RESTART";
export const GAME_CELL_SELECTED = "GAME_CELL_SELECTED";
export const GAME_REVEAL_CELLS = "GAME_REVEAL_CELLS";
export const GAME_TREASURE_CLICKED = "GAME_TREASURE_CLICKED";
